
CREATE TABLE application_train (
	sk_id_curr BIGINT, 
	target BIGINT, 
	name_contract_type TEXT, 
	code_gender TEXT, 
	flag_own_car TEXT, 
	flag_own_realty TEXT, 
	cnt_children BIGINT, 
	amt_income_total FLOAT(53), 
	amt_credit FLOAT(53), 
	amt_annuity FLOAT(53), 
	amt_goods_price FLOAT(53), 
	name_type_suite TEXT, 
	name_income_type TEXT, 
	name_education_type TEXT, 
	name_family_status TEXT, 
	name_housing_type TEXT, 
	region_population_relative FLOAT(53), 
	days_birth BIGINT, 
	days_employed BIGINT, 
	days_registration FLOAT(53), 
	days_id_publish BIGINT, 
	own_car_age FLOAT(53), 
	flag_mobil BIGINT, 
	flag_emp_phone BIGINT, 
	flag_work_phone BIGINT, 
	flag_cont_mobile BIGINT, 
	flag_phone BIGINT, 
	flag_email BIGINT, 
	occupation_type TEXT, 
	cnt_fam_members FLOAT(53), 
	region_rating_client BIGINT, 
	region_rating_client_w_city BIGINT, 
	weekday_appr_process_start TEXT, 
	hour_appr_process_start BIGINT, 
	reg_region_not_live_region BIGINT, 
	reg_region_not_work_region BIGINT, 
	live_region_not_work_region BIGINT, 
	reg_city_not_live_city BIGINT, 
	reg_city_not_work_city BIGINT, 
	live_city_not_work_city BIGINT, 
	organization_type TEXT, 
	ext_source_1 FLOAT(53), 
	ext_source_2 FLOAT(53), 
	ext_source_3 FLOAT(53), 
	apartments_avg FLOAT(53), 
	basementarea_avg FLOAT(53), 
	years_beginexpluatation_avg FLOAT(53), 
	years_build_avg FLOAT(53), 
	commonarea_avg FLOAT(53), 
	elevators_avg FLOAT(53), 
	entrances_avg FLOAT(53), 
	floorsmax_avg FLOAT(53), 
	floorsmin_avg FLOAT(53), 
	landarea_avg FLOAT(53), 
	livingapartments_avg FLOAT(53), 
	livingarea_avg FLOAT(53), 
	nonlivingapartments_avg FLOAT(53), 
	nonlivingarea_avg FLOAT(53), 
	apartments_mode FLOAT(53), 
	basementarea_mode FLOAT(53), 
	years_beginexpluatation_mode FLOAT(53), 
	years_build_mode FLOAT(53), 
	commonarea_mode FLOAT(53), 
	elevators_mode FLOAT(53), 
	entrances_mode FLOAT(53), 
	floorsmax_mode FLOAT(53), 
	floorsmin_mode FLOAT(53), 
	landarea_mode FLOAT(53), 
	livingapartments_mode FLOAT(53), 
	livingarea_mode FLOAT(53), 
	nonlivingapartments_mode FLOAT(53), 
	nonlivingarea_mode FLOAT(53), 
	apartments_medi FLOAT(53), 
	basementarea_medi FLOAT(53), 
	years_beginexpluatation_medi FLOAT(53), 
	years_build_medi FLOAT(53), 
	commonarea_medi FLOAT(53), 
	elevators_medi FLOAT(53), 
	entrances_medi FLOAT(53), 
	floorsmax_medi FLOAT(53), 
	floorsmin_medi FLOAT(53), 
	landarea_medi FLOAT(53), 
	livingapartments_medi FLOAT(53), 
	livingarea_medi FLOAT(53), 
	nonlivingapartments_medi FLOAT(53), 
	nonlivingarea_medi FLOAT(53), 
	fondkapremont_mode TEXT, 
	housetype_mode TEXT, 
	totalarea_mode FLOAT(53), 
	wallsmaterial_mode TEXT, 
	emergencystate_mode TEXT, 
	obs_30_cnt_social_circle FLOAT(53), 
	def_30_cnt_social_circle FLOAT(53), 
	obs_60_cnt_social_circle FLOAT(53), 
	def_60_cnt_social_circle FLOAT(53), 
	days_last_phone_change FLOAT(53), 
	flag_document_2 BIGINT, 
	flag_document_3 BIGINT, 
	flag_document_4 BIGINT, 
	flag_document_5 BIGINT, 
	flag_document_6 BIGINT, 
	flag_document_7 BIGINT, 
	flag_document_8 BIGINT, 
	flag_document_9 BIGINT, 
	flag_document_10 BIGINT, 
	flag_document_11 BIGINT, 
	flag_document_12 BIGINT, 
	flag_document_13 BIGINT, 
	flag_document_14 BIGINT, 
	flag_document_15 BIGINT, 
	flag_document_16 BIGINT, 
	flag_document_17 BIGINT, 
	flag_document_18 BIGINT, 
	flag_document_19 BIGINT, 
	flag_document_20 BIGINT, 
	flag_document_21 BIGINT, 
	amt_req_credit_bureau_hour FLOAT(53), 
	amt_req_credit_bureau_day FLOAT(53), 
	amt_req_credit_bureau_week FLOAT(53), 
	amt_req_credit_bureau_mon FLOAT(53), 
	amt_req_credit_bureau_qrt FLOAT(53), 
	amt_req_credit_bureau_year FLOAT(53)
)

;


CREATE TABLE bureau (
	sk_id_curr BIGINT, 
	sk_id_bureau BIGINT, 
	credit_active TEXT, 
	credit_currency TEXT, 
	days_credit BIGINT, 
	credit_day_overdue BIGINT, 
	days_credit_enddate FLOAT(53), 
	days_enddate_fact FLOAT(53), 
	amt_credit_max_overdue FLOAT(53), 
	cnt_credit_prolong BIGINT, 
	amt_credit_sum FLOAT(53), 
	amt_credit_sum_debt FLOAT(53), 
	amt_credit_sum_limit FLOAT(53), 
	amt_credit_sum_overdue FLOAT(53), 
	credit_type TEXT, 
	days_credit_update BIGINT, 
	amt_annuity FLOAT(53)
)

;


CREATE TABLE bureau_balance (
	sk_id_bureau BIGINT, 
	months_balance BIGINT, 
	status TEXT
)

;


CREATE TABLE previous_application (
	sk_id_prev BIGINT, 
	sk_id_curr BIGINT, 
	name_contract_type TEXT, 
	amt_annuity FLOAT(53), 
	amt_application FLOAT(53), 
	amt_credit FLOAT(53), 
	amt_down_payment FLOAT(53), 
	amt_goods_price FLOAT(53), 
	weekday_appr_process_start TEXT, 
	hour_appr_process_start BIGINT, 
	flag_last_appl_per_contract TEXT, 
	nflag_last_appl_in_day BIGINT, 
	rate_down_payment FLOAT(53), 
	rate_interest_primary FLOAT(53), 
	rate_interest_privileged FLOAT(53), 
	name_cash_loan_purpose TEXT, 
	name_contract_status TEXT, 
	days_decision BIGINT, 
	name_payment_type TEXT, 
	code_reject_reason TEXT, 
	name_type_suite TEXT, 
	name_client_type TEXT, 
	name_goods_category TEXT, 
	name_portfolio TEXT, 
	name_product_type TEXT, 
	channel_type TEXT, 
	sellerplace_area BIGINT, 
	name_seller_industry TEXT, 
	cnt_payment FLOAT(53), 
	name_yield_group TEXT, 
	product_combination TEXT, 
	days_first_drawing FLOAT(53), 
	days_first_due FLOAT(53), 
	days_last_due_1st_version FLOAT(53), 
	days_last_due FLOAT(53), 
	days_termination FLOAT(53), 
	nflag_insured_on_approval FLOAT(53)
)

;


CREATE TABLE installments_payments (
	sk_id_prev BIGINT, 
	sk_id_curr BIGINT, 
	num_instalment_version FLOAT(53), 
	num_instalment_number BIGINT, 
	days_instalment FLOAT(53), 
	days_entry_payment FLOAT(53), 
	amt_instalment FLOAT(53), 
	amt_payment FLOAT(53)
)

;


CREATE TABLE credit_card_balance (
	sk_id_prev BIGINT, 
	sk_id_curr BIGINT, 
	months_balance BIGINT, 
	amt_balance FLOAT(53), 
	amt_credit_limit_actual BIGINT, 
	amt_drawings_atm_current FLOAT(53), 
	amt_drawings_current FLOAT(53), 
	amt_drawings_other_current FLOAT(53), 
	amt_drawings_pos_current FLOAT(53), 
	amt_inst_min_regularity FLOAT(53), 
	amt_payment_current FLOAT(53), 
	amt_payment_total_current FLOAT(53), 
	amt_receivable_principal FLOAT(53), 
	amt_recivable FLOAT(53), 
	amt_total_receivable FLOAT(53), 
	cnt_drawings_atm_current FLOAT(53), 
	cnt_drawings_current BIGINT, 
	cnt_drawings_other_current FLOAT(53), 
	cnt_drawings_pos_current FLOAT(53), 
	cnt_instalment_mature_cum FLOAT(53), 
	name_contract_status TEXT, 
	sk_dpd BIGINT, 
	sk_dpd_def BIGINT
)

;


CREATE TABLE pos_cash_balance (
	sk_id_prev BIGINT, 
	sk_id_curr BIGINT, 
	months_balance BIGINT, 
	cnt_instalment FLOAT(53), 
	cnt_instalment_future FLOAT(53), 
	name_contract_status TEXT, 
	sk_dpd BIGINT, 
	sk_dpd_def BIGINT
)

;